language: python

python:
  - "3.6"

install:
  - "pip install flake8 pylint"

script: pytest
cache: pip

notifications:
  email: false
  webhooks:
    urls:
      - https://api.thegathering.xyz/travis/hook.php?hook=our_hook_url
    on_success: always
    on_failure: change
    on_cancel: never
    on_error: never
